apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-files-pvc
  namespace: drupal
spec:
  accessModes:
    - ReadWriteMany  #the only chagnes
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client #newly added